# Generated by Django 5.1.5 on 2025-02-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя поставщика')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон поставщика')),
                ('address', models.TextField(verbose_name='Адрес поставщика')),
            ],
        ),
    ]
