# Generated by Django 5.1.5 on 2025-02-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='address',
            new_name='supp_address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='supp_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='phone',
            new_name='supp_phone',
        ),
    ]
