# Generated by Django 5.1.5 on 2025-02-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0002_rename_address_supplier_supp_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_manufact', models.CharField(max_length=100, verbose_name='Производитель')),
                ('dev_model', models.CharField(max_length=100, verbose_name='Модель')),
                ('dev_type', models.CharField(choices=[('mouse', 'Мышь'), ('keyboard', 'Клавиатура'), ('monitor', 'Монитор'), ('printer', 'Принтер'), ('other', 'Другое')], max_length=15, verbose_name='Тип')),
                ('dev_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('dev_buydate', models.DateField(verbose_name='Дата покупки')),
                ('dev_status', models.CharField(choices=[('available', 'В наличии'), ('in_use', 'В эксплуатации'), ('repair', 'В ремонте'), ('disposed', 'Списано')], max_length=15, verbose_name='Статус')),
                ('dev_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_devices.supplier', verbose_name='Поставщик')),
            ],
        ),
    ]
