# Generated by Django 5.1.5 on 2025-02-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0003_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='dev_status',
            field=models.CharField(choices=[('available', 'На складе'), ('in_use', 'В эксплуатации'), ('repair', 'В ремонте'), ('disposed', 'Списано')], max_length=15, verbose_name='Статус'),
        ),
    ]
