# Generated by Django 5.1.5 on 2025-02-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0004_alter_devices_dev_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='dev_status',
            field=models.CharField(choices=[('На складе', 'На складе'), ('В эксплуатации', 'В эксплуатации'), ('В ремонте', 'В ремонте'), ('Списано', 'Списано')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='dev_type',
            field=models.CharField(choices=[('Мышь', 'Мышь'), ('Клавиатура', 'Клавиатура'), ('Монитор', 'Монитор'), ('Принтер', 'Принтер'), ('Другое', 'Другое')], max_length=15, verbose_name='Тип'),
        ),
    ]
