# Generated by Django 5.1.5 on 2025-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0004_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login',
            field=models.CharField(max_length=50, null=True, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='employee',
            name='us_password',
            field=models.CharField(max_length=50, null=True, verbose_name='Пароль'),
        ),
    ]
