# Generated by Django 5.1.5 on 2025-03-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0005_employee_login_employee_us_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='user', max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
