# Generated by Django 5.1.5 on 2025-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0008_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя исполнителя')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
        ),
    ]
