# Generated by Django 5.1.5 on 2025-03-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0009_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='address',
            field=models.TextField(verbose_name='Адрес '),
        ),
        migrations.AlterField(
            model_name='performer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Телефон '),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_devices.applications', verbose_name='Заявка')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_devices.performer', verbose_name='Исполнитель')),
            ],
        ),
    ]
