# Generated by Django 5.1.5 on 2025-03-27 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0010_alter_performer_address_alter_performer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='dev_buydate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обслуживания'),
            preserve_default=False,
        ),
    ]
