# Generated by Django 5.1.5 on 2025-03-31 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0011_service_dev_buydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', 'Создание устройства'), ('update', 'Изменение устройства'), ('delete', 'Удаление устройства'), ('assign', 'Передача устройства'), ('return', 'Возврат устройства')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='inventory_devices.devices')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_devices.employee')),
            ],
        ),
    ]
