# Generated by Django 5.1.5 on 2025-03-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_devices', '0012_deviceoperationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceoperationlog',
            name='operation_type',
            field=models.CharField(choices=[('Создание', 'Создание устройства'), ('Редактирование', 'Изменение устройства'), ('Удаление', 'Удаление устройства'), ('Передача', 'Передача устройства'), ('Возврат', 'Возврат устройства')], max_length=40),
        ),
    ]
